# Generated by Django 5.2.9 on 2026-01-04 16:00

import django.db.models.deletion
import vehicles.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[
                            ("bike", "Bike"),
                            ("scooter", "Scooter"),
                            ("car", "Car"),
                            ("van", "Van"),
                            ("truck", "Truck"),
                        ],
                        max_length=20,
                    ),
                ),
                ("model_name", models.CharField(max_length=120)),
                ("number_plate_no", models.CharField(max_length=50, unique=True)),
                ("license_no", models.CharField(max_length=50)),
                (
                    "license_front_photo",
                    models.ImageField(upload_to=vehicles.models.upload_vehicle_doc),
                ),
                (
                    "license_back_photo",
                    models.ImageField(upload_to=vehicles.models.upload_vehicle_doc),
                ),
                (
                    "bluebook_photo",
                    models.ImageField(upload_to=vehicles.models.upload_vehicle_doc),
                ),
                (
                    "vehicle_photo_with_plate",
                    models.ImageField(upload_to=vehicles.models.upload_vehicle_doc),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("admin_feedback", models.TextField(blank=True)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vehicle_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
